version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: task_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 33386
      POSTGRES_DB: task-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task_management_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - task_management_network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  task_management_network:
    driver: bridge
