spring:
  application:
    name: task-service
  datasource:
    url: ${DATABASE_URL}

    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db.changelog/main-changelog.xml
    enabled: true
    default-schema: public

server:
  port: ${SERVER_PORT}

log:
  execution:
    enabled: true
