spring:
  application:
    name: task-service

  config:
    import: "optional:configserver:"

server:
  port: 8095

log:
  execution:
    enabled: true

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html



