spring:
  application:
    name: task-service

  config:
    import:
      optional: configserver:http://192.168.1.10/

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
